version: "3"

services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: postgres:${POSTGRES_VERSION:-16}
        environment:
            POSTGRES_DB: tapnserve_app
            POSTGRES_PASSWORD: password
            POSTGRES_USER: tapnserve_user
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-d",
                    "tapnserve_app",
                    "-U",
                    "tapnserve_user",
                ]
            timeout: 5s
            retries: 5
            start_period: 60s
        volumes:
            - database_data:/var/lib/postgresql/data:rw
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
    ###> doctrine/doctrine-bundle ###
    database_data:
###< doctrine/doctrine-bundle ###
